### ISSUE TITLE
how i can training dataset ? plese tell me

### ISSUE THREAD

**Issue by Bhavin230** [nikkkhil067/Sign-Language-To-Text-Conversion#1]

**Comment by emnikhil** [comment]
The training data and the testing data is available in the folder **dataSet**.
And the models are available in the folder **Models**, with file named as - **Model.ipynb** which is the main file,
and all the rest models are for the data that the first model(**Model.ipynb**) was unable to recognize correctly, as this project is based on a multi - layered neural network model.

The writing convention that I have used for naming the models is like all the alphabets that a model is recognizing are written ahead of the underscore.
Like - **model-bw_dru**, which means this model is recognizing the alphabets **D, R and U**, respectively.
