### ISSUE TITLE
Unable to install pip strings

### ISSUE THREAD

**Issue by ianb445** [nikkkhil067/Sign-Language-To-Text-Conversion#6]
Hi,

I receive the below error on both Linux (Ubuntu 22.04) and Windows 10. Both have the latest versions of Python:

ubuntu@primary:~$ pip install strings
Defaulting to user installation because normal site-packages is not writeable
Collecting strings
  Downloading strings-0.1.2.tar.gz (2.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a_nua17z/strings_89a0b83f084d445dbaf23cd584f688b0/setup.py", line 5, in <module>
          import strings
      ModuleNotFoundError: No module named 'strings'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by emnikhil** [comment]
Try downgrading the Python version to 3.8, that might solve your issue.

**Comment by ianb445** [comment]
Will test and advise.

**Comment by ianb445** [comment]
Pip strings still doesn't work, however the balance of the project works under 3.8. Thanks for the help.
