### ISSUE TITLE
Can you tell me how can i add sign in this project 

### ISSUE THREAD

**Issue by rohitmanghani** [nikkkhil067/Sign-Language-To-Text-Conversion#8]
please explain

**Comment by emnikhil** [comment]
First you need to capture the new signs which you want to add, into the training and testing dataset, for that you need to run the TrainingDataCollection.py and TestingDataCollection.py files and insert the new signs which you want.
After you get the new signs, make changes in the Model.ipynb file and ad the logic for your signs.
And trying the model.

After the training is completed, make the changes to the Application.py file and add the new signs logics and then you would be able to run the project.
